# docker-compose.yml for building and development

version: "3.7"
services:

  nginx:
    build:
      context: .
      target: nginx
    ports:
      - "127.0.0.1:8080:8080"
    restart: always
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      target: php-fpm
      args:
        - APP_COMMIT=local
        - APP_VERSION=0.0.0
    volumes:
      - ./app:/var/www/html/app:ro
      - ./resources:/var/www/html/resources:ro
      - ./storage:/var/www/html/storage
    env_file: .env.docker
    restart: always

  queue-worker:
    build:
      context: .
      target: php-fpm
      args:
        - APP_COMMIT=local
        - APP_VERSION=0.0.0
    command: php artisan queue:work --sleep=3 --tries=3 --queue=default
    stop_signal: SIGTERM
    volumes:
      - ./app:/var/www/html/app:ro
      - ./resources:/var/www/html/resources:ro
      - ./storage:/var/www/html/storage
    env_file: .env.docker
    healthcheck:
      test: php artisan queue:health || exit 1
      interval: 30s
      timeout: 10s
      start_period: 15s
    restart: always

  mariadb:
    image: mariadb:10.3
    ports:
      - "127.0.0.1:33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dev_vatsim_shorturl
      MYSQL_USER: dev_vatsim_shorturl
      MYSQL_PASSWORD: secret
    restart: always
