version: "3.7"
services:

  nginx:
    build:
        context: ../
        dockerfile: ./docker/Dockerfile
        target: nginx
    ports:
      - 127.0.0.1:80:8080
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: php-fpm
    volumes:
      - app-storage:/var/www/storage
    env_file: ./.env

  queue-worker:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: php-fpm
    command: php artisan queue:work --sleep=3 --tries=3 --queue=default
    volumes:
      - app-storage:/var/www/storage
    env_file: ./.env

volumes:
  app-storage:
