version: "3.7"
services:

  nginx:
    build:
        context: ../
        dockerfile: ./docker/Dockerfile
        target: nginx
    ports:
      - 127.0.0.1:80:80

  php-fpm:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: php-fpm
    volumes:
      - /var/www/storage
    env_file: ./.env
